name: JUnit Test
on: [push]
jobs:
    JUnit-Test:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Maven Test
              run: mvn test